### ISSUE TITLE
use check-contents instead

### ISSUE THREAD

**Issue by aaronjensen** [lbolla/emacs-flycheck-flow#10]
Since flow is so fast and it supports checking buffer contents, it'd be great if this could use `check-contents` and pipe the real time buffer contents in instead of only operating on save.

**Comment by lbolla** [comment]
In this not already possible tweaking `flycheck-javascript-flow-args`? Something like:
`(customize-set-variable 'flycheck-javascript-flow-args '("check-content"))` for instance?

**Comment by aaronjensen** [comment]
No, because standard-input is not set. Is there a reason you would prefer to default to the saved-only version? Flycheck docs are clear that that is only for last resort.

**Comment by lbolla** [comment]
Just trying to not break backwards compatibility. But I guess we can be fearless.
