### ISSUE TITLE
Add react-mode to list of modes

### ISSUE THREAD

**Issue by tizoc** [lbolla/emacs-flycheck-flow#16]
I'm using a modified version of your checker with `react-mode` added to the list of modes, and so far it is working well. Are you planning to enable that?

**Comment by lbolla** [comment]
Why using a modified version of the checker? What's wrong with using `flycheck-add-mode`?

**Comment by tizoc** [comment]
@lbolla for files edited using `react-mode` (instead of `js2-mode`) flycheck will refuse to enable the checker because it is not listed here: https://github.com/lbolla/emacs-flycheck-flow/blob/master/flycheck-flow.el#L78

All I did was add `react-mode` to that list and that solved the problem for me.

**Comment by tizoc** [comment]
This is using spacemacs btw, I never noticed that the `.jsx` files were using a different mode until I saw that I wasn't getting typechecking in those files.

From looking at https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bframeworks/react/packages.el#L76

it seems `react-mode` is just derived from `web-mode` + `js2-mode`, and it is not provided by any package, it is just a spacemacs thing.

Do you know if there is another way to make flycheck use a checker without modifying the list of modes? (seeing that this is a spacemacs things, and that there are other modes that one would want to support, modifying the mode list in emacs-flycheck-flow doesn't seem so right to me now).

**Comment by tizoc** [comment]
Oh....... the function you mentioned of course :) I parsed it as `flycheck-add-next-checker`.

Thank you!
