### ISSUE TITLE
Stop using --old-output-format

### ISSUE THREAD

**Issue by mroch** [lbolla/emacs-flycheck-flow#17]
Flow is planning on removing the `--old-output-format` flag soon, probably Flow 0.37 in a few weeks. https://github.com/facebook/flow/issues/2844

Two other options that might work instead are `--json` (though I'm not an emacs user and understand that parsing JSON is challenging) and `--from emacs`. The latter uses a format that emacs should already understand, so you might not need to write a custom parser for it.

**Comment by lbolla** [comment]
Thanks!
