### ISSUE TITLE
Checker does not respect flow annotation

### ISSUE THREAD

**Issue by kmartin** [lbolla/emacs-flycheck-flow#18]
After #11, flow errors are shown regardless of whether there is a ```// @flow``` annotation at the top. The ```--respect-pragma``` argument works for this. I feel this should be the default, but that may be a matter of opinion. I would suggest at least adding a doc letting users know that the old behavior can be turned on with
```
(customize-set-variable 'flycheck-javascript-flow-args '("--respect-pragma"))
```

Thoughts on how this should behave?

**Comment by lbolla** [comment]
It's debatable what the default behavior of `flycheck-flow` should be to be honest. It looks like `flow` has taken the direction of defaulting to *not* use that switch, therefore I'd rather do the same in `flycheck-flow`, too.
In other words, I think it's wise to keep the default command line switches of `flycheck-flow` to a minimum and just allow users to overwrite them as needed.

**Comment by tomjakubowski** [comment]
> It looks like flow has taken the direction of defaulting to not use that switch, therefore I'd rather do the same in flycheck-flow, too.

They plan, or planned anyway, to make the `--respect-pragma` behavior the default here
https://github.com/facebook/flow/commit/768201006495f867e9bdfe2b922e5fa7de09f1d5#diff-bd96c357cb1f8ac0759fb9dda565aba2R68 but they haven't yet changed the default behavior.

They also choose to document --all (without saying it's a default), but not --respect-pragma, which I think is a bug as long as --all is the default behavior, so I filed a bug with the flow project here: https://github.com/facebook/flow/issues/4924
