### ISSUE TITLE
Support for jsx

### ISSUE THREAD

**Issue by Ailrun** [lbolla/emacs-flycheck-flow#23]
Can you add some support for jsx modes? (for example, js-jsx-mode, js2-jsx-mode, ....)

I want to use flow with react, and react use jsx syntaxes, that's why I write this issue.

**Comment by Ailrun** [comment]
For simple case, adding \*-jsx-\* to `:modes` is reasonable solution.

Is there any problem with it?

**Comment by lbolla** [comment]
I don't personally use `jsx` modes: if you say they work fine with flow, it's good enough for me. Please issue a PR.
