### ISSUE TITLE
Support for rjsx-mode

### ISSUE THREAD

**Issue by ccheng** [lbolla/emacs-flycheck-flow#29]
Can you add support for rjsx-mode ?

I'm using flycheck-flow for React with the rjsx-mode package.  I tried it out and it seems to work fine.

If you're okay with it, would you like me to issue a PR?

Thanks!

**Comment by lbolla** [comment]
This seems like a duplicate of https://github.com/lbolla/emacs-flycheck-flow/pull/26
Is the solution discussed there good for you?

**Comment by ccheng** [comment]
Thanks, although that solution doesn't work for me, or maybe I'm using it wrong.  But something else (not sure what) seemed to have worked, and without the addition of "rjsx-mode" in flycheck-flow.el.  Weird...

Thanks anyway, but I guess the patch I had ready is not needed now. :)
