### ISSUE TITLE
flycheck-flow not showing error

### ISSUE THREAD

**Issue by hooleyhoop** [lbolla/emacs-flycheck-flow#33]
this simple file has a [flow error](https://flow.org/try/#0PTAEAEDMBsHsHcBQ0CmAXUlawFygIIBOhAhgJ4A8AfKALygDaAuogMawB2AzrKgHRwA5gAossAJRA)
```
// @flow
let foo: Array<> = []
console.log(foo)
```

>   2: let foo: Array<> = []
>               ^^^^^^^ Incorrect number of type parameters (expected 1)

But flycheck-flow wont display it

**Comment by lbolla** [comment]
Try with the latest commit.
