### ISSUE TITLE
Unable to see Flow *and* ESLint errors in-buffer

### ISSUE THREAD

**Issue by gustavjf** [lbolla/emacs-flycheck-flow#35]
Hi, thanks for your Flow checker, I've been looking for something like this for a while.

I've encountered a problem when trying to use your Flow checker alongside the ESLint checker. I'm not sure if it's specific to your package or if it's a configuration problem on my end, but perhaps you could point me in the right direction?

I am unable to see Flycheck errors displayed in-buffer for *both* ESlint and Flow.

It's either one or the other, depending on the presence of the `.flowconfig` file when running `flow init`.

My Flycheck setup looks ok as far as I can tell:

![screenshot from 2018-06-24 16-32-07](https://user-images.githubusercontent.com/3981598/41820396-94fcf09a-77d1-11e8-852c-ae1400030fd8.png)

However, when I want to see Flow errors in-buffer as well, I initialize the Flow config, creating a skeleton `.flowconfig` in the root directory of the project. At this point, ESLint errors disappear from the buffer leaving only the errors from the Flow checker.

![screenshot from 2018-06-24 17-17-00](https://user-images.githubusercontent.com/3981598/41820455-781a3734-77d2-11e8-8d11-8a42e2b35fdc.png)

Here is a reproduction case I've set up that hopefully demonstrates my problem: https://github.com/gustavjf/flycheck-issue-repro

Emacs Version: Emacs 26.1 (terminal, not GUI)
Emacs Config: https://github.com/gustavjf/emacs.d
Custom flycheck config: https://github.com/gustavjf/emacs.d/blob/5c277dc7de67dcaae308a57eee3e9ee4712a84fc/lisp/custom/init-flycheck-extended.el#L1
OS: Debian-based linux distro

I should be able to have both ESLint and Flow errors display in-buffer with this configuration and the missing `.flowconfig`, right?

Happy to provide any other info if necessary.

**Comment by lbolla** [comment]
Try to `append` to next checker list instead of `prepend`, i.e. use `(flycheck-add-next-checker 'javascript-eslint 'javascript-flow t)` (with the `t` at the end). I don't use `eslint` myself to try it out.

**Comment by gustavjf** [comment]
Hi @lbolla, thanks for the tip. Unfortunately, the effects are the same after changing that.

Strangely enough, I noticed I was able to see both flow and eslint errors displayed in the buffer on my macOS machine, without your suggestion. I'll go ahead and close as it doesn't appear to be a problem with your package.
