### ISSUE TITLE
Multiline error message

### ISSUE THREAD

**Issue by dgellow** [lbolla/emacs-flycheck-flow#5]
Currently when using flycheck-flow errors are displayed as one line.
<img width="630" alt="screen shot 2015-10-27 at 07 58 13" src="https://cloud.githubusercontent.com/assets/2451004/10751452/b4909af0-7c80-11e5-8dba-3cc2b7f03afe.png">

It would be better to present them on multiple lines. Maybe it could be done by just replacing `\n` with the newline character (made with `C-q C-j` in emacs)?
I searched a solution on flycheck documentation and issues/pull requests but without success.

Any thoughts?

**Comment by lbolla** [comment]
Without using "--one-line" and using the regex that was removed by this commit (https://github.com/lbolla/emacs-flycheck-flow/commit/af8ba09de53fe1fcb1f57c62813a2267a2e31764), the output would be as attached, which I think looks nicer.
![screenshot from 2015-10-27 22 09 53](https://cloud.githubusercontent.com/assets/20991/10774151/7d86d2a0-7cf7-11e5-9370-b7079fb05ca1.png)

**Comment by dgellow** [comment]
@lbolla Yeah, much better :) Thank you
