### ISSUE TITLE
Contribute to Flycheck

### ISSUE THREAD

**Issue by swsnr** [lbolla/emacs-flycheck-flow#6]
Hey,

would you like to contribute this syntax checker to Flycheck?  I'd be happy to add it :relaxed:

**Comment by lbolla** [comment]
@lunaryorn flycheck-flow is already available in melpa: my pull request was accepted not long ago (https://github.com/milkypostman/melpa/pull/3135).
Do you want to make it part of the standard flycheck distribution?

**Comment by swsnr** [comment]
@lbolla Yes that was my idea. It'd be great to support it out of the box 😊

**Comment by lbolla** [comment]
Sure. I will issue a pull request to https://github.com/flycheck/flycheck.

**Comment by arronmabrey** [comment]
@lbolla do you have a pointer to the PR on https://github.com/flycheck/flycheck?

**Comment by lbolla** [comment]
@arronmabrey https://github.com/flycheck/flycheck/pull/789

**Comment by arronmabrey** [comment]
@lbolla thx! :-)
