### ISSUE TITLE
Allow to use `flow status` instead of `flow check`

### ISSUE THREAD

**Issue by c089** [lbolla/emacs-flycheck-flow#8]
Currently this package always runs `flow check`, doing a full type check which can quickly get very slow (>10seconds). By calling `flow status` instead of `flow check` I can get results instantly and wonder if there's a reason this package always runs `check` or if it should be changed to `status` or at least made configurable?

**Comment by lbolla** [comment]
Fixed in https://github.com/lbolla/emacs-flycheck-flow/commit/9d0787c0ea6b17362c8255a3c8859ca76efd2242

Can you give it a whirl?

**Comment by c089** [comment]
Awesome, much faster now :) Thank you
